# 공통 설정
spring:
  web:
    resources:
      cache:
        cachecontrol:
          cache-public: true
        use-last-modified: true
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

---
spring:
  config:
    activate:
      on-profile: local

  web:
    resources:
      cache:
        cachecontrol:
          max-age: 0  # 개발 시 캐시 비활성화

---
spring:
  config:
    activate:
      on-profile: dev

  web:
    resources:
      cache:
        cachecontrol:
          max-age: 1800  # 30분

---
spring:
  config:
    activate:
      on-profile: prd

  web:
    resources:
      cache:
        cachecontrol:
          max-age: 86400  # 24시간