---
spring:
  config:
    activate:
      on-profile: local

jwt:
  access-token-expiration: 1440      # 1시간 (분 단위)
  refresh-token-expiration: 20160  # 2주 (분 단위)

---
spring:
  config:
    activate:
      on-profile: dev

jwt:
  access-token-expiration: 1440      # 1시간 (분 단위)
  refresh-token-expiration: 20160  # 2주 (분 단위)

---
spring:
  config:
    activate:
      on-profile: prd

jwt:
  access-token-expiration: 1440      # 1시간 (분 단위)
  refresh-token-expiration: 20160  # 2주 (분 단위)
