springdoc:
  cache:
    disabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

---
spring:
  config:
    activate:
      on-profile: local

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html  # 접속 경로
    tags-sorter: alpha      # 태그 알파벳 정렬
    operations-sorter: method  # GET, POST, 등 정렬
  api-docs:
    path: /api/v3/api-docs

---
spring:
  config:
    activate:
      on-profile: dev

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html  # 접속 경로
    tags-sorter: alpha      # 태그 알파벳 정렬
    operations-sorter: method  # GET, POST, 등 정렬
  api-docs:
    path: /api/v3/api-docs
---
spring:
  config:
    activate:
      on-profile: prd

springdoc:
  swagger-ui:
    path: /api/swagger-ui.html  # 접속 경로
    tags-sorter: alpha      # 태그 알파벳 정렬
    operations-sorter: method  # GET, POST, 등 정렬
  api-docs:
    path: /api/v3/api-docs