server:
  shutdown: graceful          # graceful shutdown 활성화 (기본값: immediate)
spring:
  application:
    name: minehair
  config:
    import:
      - classpath:application-db.yml
      - classpath:application-swagger.yml
  lifecycle:
    timeout-per-shutdown-phase: 30s  # 각 셧다운 단계별 최대 대기 시간



