# 공통 설정

---
spring:
  config:
    activate:
      on-profile: local

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

---
spring:
  config:
    activate:
      on-profile: dev

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

---
spring:
  config:
    activate:
      on-profile: prd

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB