
spring:
  application:
    name: minehair
  config:
    import:
      - classpath:application-db.yml
      - classpath:application-swagger.yml
      - classpath:application-web.yml
      - classpath:application-server.yml
  lifecycle:
    timeout-per-shutdown-phase: 30s  # 각 셧다운 단계별 최대 대기 시간



